Script: Updating smart update script

diff --git a/recipes-tools/crimson-filesystem/crimson-filesystem/etc/crimson/crimson-smart-update b/recipes-tools/crimson-filesystem/crimson-filesystem/etc/crimson/crimson-smart-update
--- a/recipes-tools/crimson-filesystem/crimson-filesystem/etc/crimson/crimson-smart-update
+++ b/recipes-tools/crimson-filesystem/crimson-filesystem/etc/crimson/crimson-smart-update
@@ -9,91 +9,147 @@ ok="[$green   OK   $normal]"
 failed="[$red FAILED $normal]"
 warning="[$yellow WARNING$normal]"
 
-function stoping_services {
-	systemctl stop crimson-website &&
-	systemctl stop crimson-server
-}
+case "$1" in
+stop)
+	if [[ -z "$2" ]]; then
+		echo "Service name cannot be empty"
+		exit 1
+	fi
+	echo "Stopping system service $2..."
+	systemctl stop $2
+	rc=$?
+	if [[ $rc != 0 ]]; then
+		echo -e "$failed Failed to stop crimson services, exiting..."
+		echo -e "$bold Try xx to fix the problem"
+		exit $rc
+	fi
+	echo -e "$ok Done"
+	;;
 
-function smart_update {
-	smart update &&
-	smart upgrade crimson-mcu crimson-fpga crimson-firmware crimson-website &&
-	smart upgrade crimson-website
-}
+start)
+	if [[ -z "$2" ]]; then
+		echo "Service name cannot be empty"
+		exit 1
+	fi
+	echo "Starting system service $2..."
+	systemctl start $2
+	rc=$?
+	if [[ $rc != 0 ]]; then
+		echo -e "$failed Failed to stop crimson services, exiting..."
+		echo -e "$bold Try xx to fix the problem"
+		exit $rc
+	fi
+	echo -e "$ok Done"
+	;;
 
-function server_cleanup {
-	umount /var/crimson/state &&
-	rm -rf /var/crimson/state &&
-	mkdir /var/crimson/state &&
-	mount -t tmpfs -o size=50m tpmfs /var/crimson/state
-}
+update_db)
+	echo "Updating package manager database..."
+	smart update
+	rc=$?
+	if [[ $rc != 0 ]]; then
+		echo -e "$failed Failed to update package manager database, exiting..."
+		echo -e "$bold Try xx to fix the problem"
+		exit $rc
+	fi
+	echo -e "$ok Done"
+	;;
 
-function mcu_update {
-	cd /lib/mcu && 
-	./flash w time crimson &&
-	./flash w rx crimson &&
-	./flash w tx crimson
-}
+remove)
+	if [[ -z "$2" ]]; then
+		echo "Package name cannot be empty"
+		exit 1
+	fi
+	echo "Removing package $2..."
+	smart remove $2
+	rc=$?
+	if [[ $rc != 0 ]]; then
+		echo -e "$failed Failed to remove package $2, exiting..."
+		echo -e "$bold Try xx to fix the problem"
+		exit $rc
+	fi
+	echo -e "$ok Done"
+	;;
 
-function fpga_update {
-	cd /lib/firmware &&
-	./update.sh hard
-}
+install)
+	if [[ -z "$2" ]]; then
+		echo "Package name cannot be empty"
+		exit 1
+	fi
+	echo "Installing package $2..."
+	smart install $2
+	rc=$?
+	if [[ $rc != 0 ]]; then
+		echo -e "$failed Failed to install package $2, exiting..."
+		echo -e "$bold Try xx to fix the problem"
+		exit $rc
+	fi
+	echo -e "$ok Done"
+	;;
 
-function restarting_services {
-	systemctl unmask crimson-server &&
-	systemctl enable crimson-server &&
-	systemctl unmask crimson-website &&
-	systemctl enable crimson-website
-}
+upgrade)
+	if [[ -z "$2" ]]; then
+		echo "Package name cannot be empty"
+		exit 1
+	fi
+	echo "Upgrading package $2..."
+	smart upgrade $2
+	rc=$?
+	if [[ $rc != 0 ]]; then
+		echo -e "$failed Failed to upgrade package $2, exiting..."
+		echo -e "$bold Try xx to fix the problem"
+		exit $rc
+	fi
+	echo -e "$ok Done"
+	;;
 
-stoping_services
-rc0=$?
-if [[ $rc0 != 0 ]]; then
-	echo -e "$failed Failed to stop system services, exiting..."
-	echo -e "$bold Try xx to fix the problem"
-	exit $rc0
-fi
-echo -e "$ok Finish stopping system services"
-smart_update
-rc1=$?
-if [[ $rc1 != 0 ]]; then
-	echo -e "$failed Failed to execute smart update, exiting..."
-	echo -e "$bold Try xx to fix the problem"
-	exit $rc1
-fi
-echo -e "$ok Finish executing smart update"
-server_cleanup
-rc2=$?
-if [[ $rc2 != 0 ]]; then
-	echo -e "$failed Failed to execute server cleanup, exiting..."
-	echo -e "$bold Try xx to fix the problem"
-	exit $rc2
-fi
-echo -e "$ok Finish executing server cleanup"
-mcu_update
-rc3=$?
-if [[ $rc3 != 0 ]]; then
-	echo -e "$failed Failed to execute mcu update, exiting..."
-	echo -e "$bold Try xx to fix the problem"
-	exit $rc3
-fi
-echo -e "$ok Finish executing mcu update"
-fpga_update
-rc4=$?
-if [[ $rc4 != 0 ]]; then
-	echo -e "$failed Failed to execute fpga update, exiting..."
-	echo -e "$bold Try xx to fix the problem"
-	exit $rc4
-fi
-echo -e "$ok Finish executing fpga update"
-restarting_services
-rc5=$?
-if [[ $rc5 != 0 ]]; then
-	echo -e "$failed Failed to restart system services, exiting..."
-	echo -e "$bold Try xx to fix the problem"
-	exit $rc5
-fi
-echo -e "$ok Finish restarting system services"
-sync
-sleep 15
-systemctl reboot
+flash)
+	if [[ -z "$2" ]]; then
+		echo "Board name cannot be empty"
+		exit 1
+	fi
+	if [[ "$2" == "dig" && "$3" == "soft" ]]; then
+		echo "Flashing FPGA on $2..."
+		cd /lib/firmware && ./update.sh soft
+	elif [[ "$2" == "dig" && "$3" == "hard" ]]; then
+		echo "Flashing FPGA and SD card on $2..."
+		cd /lib/firmware && ./update.sh hard
+	else
+		echo "Flashing MCU on $2..."
+		cd /lib/mcu && ./flash w $2 crimson
+	fi
+	rc=$?
+	if [[ $rc != 0 ]]; then
+		echo -e "$failed Failed to flash $2, exiting..."
+		echo -e "$bold Try xx to fix the problem"
+		exit $rc
+	fi
+	echo -e "$ok Done"
+	;;
+
+cleanup)
+	if [[ "$2" != "crimson-server" ]]; then
+		echo -e "$failed Only crimson-server cleanup function is supported"
+		exit 1
+	else
+		echo "Cleaning up server..."
+		umount /var/crimson/state &&
+		rm -rf /var/crimson/state &&
+		mkdir /var/crimson/state &&
+		mount -t tmpfs -o size=50m tpmfs /var/crimson/state
+	fi
+	rc=$?
+	if [[ $rc != 0 ]]; then
+		echo -e "$failed Failed to cleanup server, exiting..."
+		echo -e "$bold Try xx to fix the problem"
+		exit $rc
+	fi
+	echo -e "$ok Done"
+	;;
+
+*)
+	echo -e "$bold Usage: Under Construction $normal"
+	exit 1
+	;;
+
+esac
+exit 0
